[Feat] Developed Navbar that is variable page by page
PoFoLo/PoFoLo-FE pull request #2
Opened 2024-11-06 16:10 UTC by DavidnotBeckham

## 📎 Details
### ✨ Using Props
- I utilized props to make the navbar variable page by page and based on whether the user is logged in or not. It can also change its pictures according to the current page.
### ✨ Not just using image component
- Utilized a SVG code not to use an image component for the button at the rightmost.

### ❕ Common
- Split logo on the left and three buttons on the right.

## 📎 Screenshots
![1  미로그인 상태](https://github.com/user-attachments/assets/d3b253d5-e5c7-4b93-afaa-ab57c75a58f2)
---
![2  로그인 중 및 마이페이지 접속 중 상태](https://github.com/user-attachments/assets/a92aa53d-14b0-43eb-972d-8762d91ea0ca)

2024-11-07 07:00 UTC, letthem requested changes
수고해써용 !!! 리뷰 수정해서 또 commit 하고, git push origin feat/layout 에 하면 그대로 pr 에 반영되니까 그렇게 해줘!

2024-11-07 07:00 UTC, letthem commented on src/assets/webps/Navbar/navbarLogo.webp
로고 이렇게 가져오지 말고
<img width="565" alt="image" src="https://github.com/user-attachments/assets/599840dc-ff08-40dd-b0e6-7bc3315528fc">

이렇게 딱 맞춰서 가져오세용
<img width="356" alt="image" src="https://github.com/user-attachments/assets/942279b4-5049-46fd-ad4f-2a062f416739">

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  height: 42px;
NavContainer는 width: 100vw, height: 64px로 맞춰주고, z-index도 10정도로 주세요. 위치 fixed로 고정시켜주고! 그리고 flex로 justify-content랑 align-items center 줘서 그 안에 지금 만든 부분을 넣어서 중앙에 맞춰주세요. 그리고 모든 px들 나누기 10 해서 rem 으로 써주세요!

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/9ecdfb4e-eca2-4181-89a3-126560d2d30e">

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +              <S.IconContainer xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 14">
svg는 이렇게 불러오지 말고, assets/svgs/Navbar에 logoutIcon.svg 이런식으로 넣어서 webp 처럼 import로 불러와서 img src 로 사용해주세요

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +  const handleNavigate = (page: 'home' | 'myPage' | 'serviceIntro' | 'login') => {
serviceIntro 경로 그냥 단순 '/' 입니다 ! 그냥 우리 서비스 들어오면 서비스 소개 페이지(온보딩)라 수정해주세요.
그리고 경로에 대문자 넣지 마세요 ! mypage 이런식으로 바꿔주세용

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +  onNavigate: (page: 'home' | 'myPage' | 'serviceIntro' | 'login') => void;
onNavigate 없애주세요 useNavigate랑 중복돼서 동작을 안 합니다.

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +        <S.Logo src={logoSrc} alt="Logo" onClick={() => handleNavigate('home')} />
/project/write와 /project/:projectId 에서는 PoFoLo 로고 대신 < 아이콘이 보여야 하고, 해당 버튼을 클릭하면 navigate(-1) 기능이 들어가야합니다. 추가해주세요!

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +export const NavLink = styled.span<{ width: number }>`
여기서 폰트 subhead2 로 쓰면 됩니다.
color도 theme에 있는 거 쓰세요!

즉, 

${(props) => props.theme.fonts.subhead2};
color: ${(props) => props.theme.colors.gray80};

이렇게 사용해주세요.

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +export const LoginButton = styled.button`
여기도 마찬가지로

${(props) => props.theme.fonts.subhead3};
color: ${(props) => props.theme.colors.gray70};

이렇게 써주세요

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  font-size: 15px;
현재 15px로 되어있는 이유가 있나요?

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  border: 0.75px solid var(--Gray-20, #e4e4e6);
이런 부분도 theme에 있는 걸로 쓰세용 모든 color와 font는 theme에 있는걸로 씁니다.

border: 0.075rem solid ${(props) => props.theme.colors.blue50};

이런식으로 써주세용

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  background: #fff;
white는 ${(props) => props.theme.colors.white};

이렇게 쓰기 번거로우니 그냥 background-color: white; 이렇게 맞춥시당

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  background: url(<path-to-image>) lightgray -16.206px -7.452px / 190.909% 143.182% no-repeat;
이렇게 하지말구 Button 자체는 border-radius: 50%,  overflow: hidden 인 원 모양 div로 하고 안에 img src 크기 지정해서 꽉 채워서 씁시다. 원 밖으로 튀어나온 사진은 못 쓰도록

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  background: url(<path-to-image>) lightgray -16.206px -7.452px / 190.909% 143.182% no-repeat;
이거 지금 코드 피그마에서 그대로 가져온것같은데 이렇게 쓰지 맙시다 !! 그냥 이미지로 불러와유 border도 없애고

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  border: 1.5px solid var(--Gray-20, #e4e4e6);
border 없앱시당

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  background: var(--Gray-05, #f8f8f8);
background 색상만 있을 땐 그냥 background-color: ${(props) => props.theme.colors.gray05}; 이렇게 씁시다. background 말궁

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  color: var(--Gray-30, #c9cacf);
여기도 color, font theme에서 불러와유

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  fill: var(--Gray-30, #c9cacf);
fill 필요없습니당 svg는 그냥 import 해서 씁시다 !

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +export const IconContainer = styled.svg`
이거 svg 말고 img 로 바꿉시다

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +interface NavbarProps {
Navbar에 props가 이렇게 많이 필요한 이유가 있나요?

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +interface NavbarProps {
페이지들을   const location = useLocation(); 

이런식으로 useLocation 써서 해당 페이지 링크에 따라 다르게 보이게 합시다. 로그인 로그아웃은 나중에 로그인 연결하고 추가해도 되니까 우선 지금은 
<img width="200" alt="image" src="https://github.com/user-attachments/assets/83ca119f-504f-43fa-b9d9-70afe02e5863">
PoFoLo가 보이냐 < 가 보이냐 위주로 짜주세요 !! NavBar에 props를 붙여 가져오는게 조금 그런것같습니당

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +  logoSrc?: string;
지금 이 src들도 props로 받지 말고 그냥 import해서 써주세요

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +  myPageSrc?: string;
이것도 마찬가지 ! 나중에 사진 연결하면 되니까 props 로 쓰지 맙시다. 지금은 기본 이미지만 import 해서 쓰세요

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +  isLoggedIn: boolean;
로그인 관련은 나중에 추가합시다. 아직 온보딩 -> 로그인 디자인도 안 나와서 개발하기까지 좀 걸릴 것 같으니, 이 props도 없애고 로그인 로그아웃 버튼은 우선 주석처리하고(없애진 말고!!), 살려놓을 UI는 우선 로그인 된 버전, 즉 defaultMyPageSrc로 보이게 해서 mypage로만 연결해주세용

2024-11-07 07:00 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +  currentPage: 'home' | 'myPage' | 'serviceIntro';
이것도 useLocation 써서 Navbar에 props 없앱시다 !!

2024-11-07 16:20 UTC, yes-david commented on src/components/Layout/Navbar/styles.ts
> +  font-size: 15px;
현재는 Pretendard가 적용되지 않은 다른 글꼴이라 16픽셀로 하면 규격을 벗어나요!!

2024-11-07 16:32 UTC, yujeong430 commented on src/components/Layout/Navbar/styles.ts
> +  font-size: 15px;
<img width="214" alt="image" src="https://github.com/user-attachments/assets/ea9621f4-29df-4553-8b22-97fbbecfdf8c">

styles > theme.ts 에 폰트 스타일 다 설정되어있어서 피그마 보고 `${(props) => props.theme.fonts.caption2};` 이런식으로 갖다 쓰면 적용 돼요!

2024-11-07 17:01 UTC, DavidnotBeckham commented on src/components/Layout/Navbar/Navbar.tsx
> +  isLoggedIn: boolean;
ㅇㅋ.. 미리 로그인 고려할 필요 없었구나 ㅠ props도 너무 많이 걱정해서 한 건데 괜히 했네 우리 시간 없는데

2024-11-08 07:20 UTC, letthem commented
<img width="1707" alt="스크린샷 2024-11-08 오후 4 19 20" src="https://github.com/user-attachments/assets/3bb9c10b-e017-48e1-840b-e1d5f4301abb">

< 버튼 크기 지정해주세요 ! 그리고 Navbar 이렇게 길게 안 보이도록 한 번 더 감싸주세요

2024-11-08 07:20 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +// 추후 Pretendard 글꼴 적용 시 원안인 font-size: 1.6rem로 바꾸기
이런 주석 없애주세요!

2024-11-08 07:20 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +// 추후 Pretendard 글꼴 적용 시 원안인 font-size: 1.6rem로 바꾸기
여기 주석도 다 지워주세요!

2024-11-08 07:21 UTC, letthem approved these changes

2024-11-08 07:23 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  height: 42px;
이 부분 다시 참고하고 반영해주세요!! ⭐️⭐️⭐️

2024-11-08 07:25 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  height: 42px;
NavContainer(width: 100vw, height: 64px) 안에 그 전에 만들었던 걸(width:1312px, height: 42px 짜리 div) 중앙 정렬해서 넣어야한다는 말!!

2024-11-09 07:17 UTC, letthem commented on src/assets/webps/Navbar/navbarGoBack.webp
뒤로가기 이미지는 Common 에 넣어줘 ! profileLogo 도 마찬가지로 Common에 넣어줘
<img width="842" alt="image" src="https://github.com/user-attachments/assets/669c8d96-a245-45c3-ae98-ada406b6ec95">

2024-11-09 17:14 UTC, letthem commented on src/App.tsx
> +            <Route path="/" element={<Home />} />
ㅠ.ㅠ App.tsx 라우팅 경로 바꾸지 마세요..,.,.,.,,,,, 
```
<Route path="/" element={<AboutPage />} />
<Route path="/home" element={<MainPage />} />
<Route path="/project/:projectId" element={<ProjectDetailPage />} />
<Route path="/project/write" element={<WriteProjectPage />} />
```

얘네 다 어디갔슴까 .ㅜㅜ.ㅜ.ㅜ.

2024-11-09 17:19 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  width: 100%;
반응형(1440 미만) 일때 양 옆 여백도 추가해주세요!!!

2024-11-09 17:25 UTC, letthem commented on src/App.tsx
> +  height: 100vh;
height 랑 overflow 없애주세요

2024-11-09 17:25 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  width: 100%;
background-color: white; 도 추가해주세용

2024-11-09 17:27 UTC, letthem commented
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/e6d50bc7-3a01-4081-b226-4a5d678d7d36">
이 부분은 여전히 수정 안 되어있습니당 !! PR 리뷰 수정 된 부분은 이모지 달아주세용 그럼 다들 작업하기 더 편할 것 같아!!

2024-11-10 01:57 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +    padding: 0 10rem;
<img width="271" alt="스크린샷 2024-11-10 오전 10 57 05" src="https://github.com/user-attachments/assets/183686ee-6fa7-4b67-87eb-9eee5c01ffbb">

여백 6.4rem 입니다!
padding: 0 6.4rem; 으로 수정해주세용

2024-11-10 01:59 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +export const GoBack = styled.img`
cursor: pointer; 추가합시다 !

2024-11-10 02:10 UTC, letthem commented
그리구 폴더 보면 예전에 만들어놓은 NavBar 폴더가 한 번 깃에 올라갔는지 비어있는 폴더가 계속 있는데

<img width="186" alt="스크린샷 2024-11-10 오전 11 00 48" src="https://github.com/user-attachments/assets/fa257e2f-11f2-4e05-9413-ab0b97bfcb30">

---

터미널에 `git clean -d -i` 입력하면

<img width="539" alt="스크린샷 2024-11-10 오전 11 06 55" src="https://github.com/user-attachments/assets/954bb3d0-2958-4d68-82d2-48e98a7be079">

이렇게 뜨거든? 
1. `3` 입력해서 select by numbers 한 다음에 
2. src/components/NavBar/ 있는 거 번호 또 누르고 
3. `1` 입력해서 clean 해주고 
4. "[Remove] Delete NavBar Folder" 로 커밋한 다음 
5. 다시 push 해줘!!


https://velog.io/@modolee/clean-empty-directory-from-local-git-repo

이런 거 참고행 첨부터 1 clean 누르지 말고 첨에는 3번 눌러서 선택해서 지워!!

2024-11-10 02:11 UTC, letthem commented
거의 다왔다 수고해써!! 🥹🥹

2024-11-10 02:12 UTC, letthem commented on src/components/Layout/Navbar/Navbar.tsx
> +import navbarLogoutSrc from '@/assets/svgs/Navbar/navbarLogout.svg';
여기도 우선 지금 안 쓰니까 주석처리해줘!

2024-11-10 02:15 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  /* NavLeft는 로고를 왼쪽에 고정 */
여기도 width, height 지정해주세요!


<img width="241" alt="스크린샷 2024-11-10 오전 11 14 54" src="https://github.com/user-attachments/assets/e4ee8f1e-a6f0-45c5-9611-a60cc128ec05">

2024-11-10 09:13 UTC, DavidnotBeckham commented
> 그리구 폴더 보면 예전에 만들어놓은 NavBar 폴더가 한 번 깃에 올라갔는지 비어있는 폴더가 계속 있는데
> 
> <img alt="스크린샷 2024-11-10 오전 11 00 48" width="186" src="https://private-user-images.githubusercontent.com/81095801/384653304-fa257e2f-11f2-4e05-9413-ab0b97bfcb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAwODgsIm5iZiI6MTczMTIyOTc4OCwicGF0aCI6Ii84MTA5NTgwMS8zODQ2NTMzMDQtZmEyNTdlMmYtMTFmMi00ZTA1LTk0MTMtYWIwYjk3YmZjYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGI1NjdmMmZmZTdhNzVhNGUwZDBmZWI0ZjNjMzQwYmY5OWFhZDAwZDFkNjhhNzJlZTQ3NzllMTUyNTM2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LlkWSaSxm4bYmYCpuM5JukFfZFs6uJN9PLfo6pCPpQE">
> 터미널에 `git clean -d -i` 입력하면
> 
> <img alt="스크린샷 2024-11-10 오전 11 06 55" width="539" src="https://private-user-images.githubusercontent.com/81095801/384653512-954bb3d0-2958-4d68-82d2-48e98a7be079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAwODgsIm5iZiI6MTczMTIyOTc4OCwicGF0aCI6Ii84MTA5NTgwMS8zODQ2NTM1MTItOTU0YmIzZDAtMjk1OC00ZDY4LTgyZDItNDhlOThhN2JlMDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzUzODk3OGRhMzRhNDBiOTA4Mjk2ODVkMmI4ODE1ZTFhMGUwM2FjOWJlMDczZWJmMmFkMzkzZDM1MmFmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HOQMxVaBpKWLpowJNz2UICn8GNJ2ilPZDNm9cmyuy_E">
> 이렇게 뜨거든?
> 
> 1. `3` 입력해서 select by numbers 한 다음에
> 2. src/components/NavBar/ 있는 거 번호 또 누르고
> 3. `1` 입력해서 clean 해주고
> 4. "[Remove] Delete NavBar Folder" 로 커밋한 다음
> 5. 다시 push 해줘!!
> 
> https://velog.io/@modolee/clean-empty-directory-from-local-git-repo
> 
> 이런 거 참고행 첨부터 1 clean 누르지 말고 첨에는 3번 눌러서 선택해서 지워!!

2024-11-10 09:15 UTC, DavidnotBeckham commented
> > 그리구 폴더 보면 예전에 만들어놓은 NavBar 폴더가 한 번 깃에 올라갔는지 비어있는 폴더가 계속 있는데
> > <img alt="스크린샷 2024-11-10 오전 11 00 48" width="186" src="https://private-user-images.githubusercontent.com/81095801/384653304-fa257e2f-11f2-4e05-9413-ab0b97bfcb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAwODgsIm5iZiI6MTczMTIyOTc4OCwicGF0aCI6Ii84MTA5NTgwMS8zODQ2NTMzMDQtZmEyNTdlMmYtMTFmMi00ZTA1LTk0MTMtYWIwYjk3YmZjYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGI1NjdmMmZmZTdhNzVhNGUwZDBmZWI0ZjNjMzQwYmY5OWFhZDAwZDFkNjhhNzJlZTQ3NzllMTUyNTM2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LlkWSaSxm4bYmYCpuM5JukFfZFs6uJN9PLfo6pCPpQE">
> > 터미널에 `git clean -d -i` 입력하면
> > <img alt="스크린샷 2024-11-10 오전 11 06 55" width="539" src="https://private-user-images.githubusercontent.com/81095801/384653512-954bb3d0-2958-4d68-82d2-48e98a7be079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAwODgsIm5iZiI6MTczMTIyOTc4OCwicGF0aCI6Ii84MTA5NTgwMS8zODQ2NTM1MTItOTU0YmIzZDAtMjk1OC00ZDY4LTgyZDItNDhlOThhN2JlMDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzUzODk3OGRhMzRhNDBiOTA4Mjk2ODVkMmI4ODE1ZTFhMGUwM2FjOWJlMDczZWJmMmFkMzkzZDM1MmFmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HOQMxVaBpKWLpowJNz2UICn8GNJ2ilPZDNm9cmyuy_E">
> > 이렇게 뜨거든?
> > 
> > 1. `3` 입력해서 select by numbers 한 다음에
> > 2. src/components/NavBar/ 있는 거 번호 또 누르고
> > 3. `1` 입력해서 clean 해주고
> > 4. "[Remove] Delete NavBar Folder" 로 커밋한 다음
> > 5. 다시 push 해줘!!
> > 
> > https://velog.io/@modolee/clean-empty-directory-from-local-git-repo
> > 이런 거 참고행 첨부터 1 clean 누르지 말고 첨에는 3번 눌러서 선택해서 지워!!



> 그리구 폴더 보면 예전에 만들어놓은 NavBar 폴더가 한 번 깃에 올라갔는지 비어있는 폴더가 계속 있는데
> 
> <img alt="스크린샷 2024-11-10 오전 11 00 48" width="186" src="https://private-user-images.githubusercontent.com/81095801/384653304-fa257e2f-11f2-4e05-9413-ab0b97bfcb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAwODgsIm5iZiI6MTczMTIyOTc4OCwicGF0aCI6Ii84MTA5NTgwMS8zODQ2NTMzMDQtZmEyNTdlMmYtMTFmMi00ZTA1LTk0MTMtYWIwYjk3YmZjYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGI1NjdmMmZmZTdhNzVhNGUwZDBmZWI0ZjNjMzQwYmY5OWFhZDAwZDFkNjhhNzJlZTQ3NzllMTUyNTM2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LlkWSaSxm4bYmYCpuM5JukFfZFs6uJN9PLfo6pCPpQE">
> 터미널에 `git clean -d -i` 입력하면
> 
> <img alt="스크린샷 2024-11-10 오전 11 06 55" width="539" src="https://private-user-images.githubusercontent.com/81095801/384653512-954bb3d0-2958-4d68-82d2-48e98a7be079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzAwODgsIm5iZiI6MTczMTIyOTc4OCwicGF0aCI6Ii84MTA5NTgwMS8zODQ2NTM1MTItOTU0YmIzZDAtMjk1OC00ZDY4LTgyZDItNDhlOThhN2JlMDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA5MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNzUzODk3OGRhMzRhNDBiOTA4Mjk2ODVkMmI4ODE1ZTFhMGUwM2FjOWJlMDczZWJmMmFkMzkzZDM1MmFmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HOQMxVaBpKWLpowJNz2UICn8GNJ2ilPZDNm9cmyuy_E">
> 이렇게 뜨거든?
> 
> 1. `3` 입력해서 select by numbers 한 다음에
> 2. src/components/NavBar/ 있는 거 번호 또 누르고
> 3. `1` 입력해서 clean 해주고
> 4. "[Remove] Delete NavBar Folder" 로 커밋한 다음
> 5. 다시 push 해줘!!
> 
> https://velog.io/@modolee/clean-empty-directory-from-local-git-repo
> 
> 이런 거 참고행 첨부터 1 clean 누르지 말고 첨에는 3번 눌러서 선택해서 지워!!

![캡처1](https://github.com/user-attachments/assets/71e6274a-f3f0-4f21-a019-889d7dcd8526)
![캡처](https://github.com/user-attachments/assets/98c22d55-b7cb-4eb9-873a-84a3f54c0b9f)

$ git clean -d -i 해도 이렇게 뜨는데 삭제가 이미 된 거 아니야??
Would remove the following item:
  src/assets/webps/Main/
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers
    4: ask each             5: quit                 6: help
What now> 3
    1: src/assets/webps/Main/

2024-11-10 09:29 UTC, DavidnotBeckham commented
Unintended closure of the PR. Reopening it.

2024-11-10 09:49 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +    padding: 0 10rem;
미디어 쿼리 부분도 ,, 지금 0 10rem으로 되어있오

2024-11-10 09:50 UTC, letthem commented on src/components/Layout/Navbar/styles.ts
> +  /* NavLeft는 로고를 왼쪽에 고정 */
이거 추가 부탁 !

2024-11-10 16:15 UTC, letthem commented on src/App.tsx
App.tsx 라우팅 건드리지 말아주세요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 
Navbar 모든 페이지에 다 보이게 하는 건 좋은데 라우팅을 건들면 우리가 열심히 만든 페이지가 안 보입니다,,,

2024-11-10 16:18 UTC, DavidnotBeckham commented on src/App.tsx
테스트 해보고 까먹네요 죄송합니다 ㅠ 슬랙 보내기 전에 복구해서 커밋했는데 반영이 안 되었나요?

@DavidnotBeckham
[[Fix] Restored App.tsx after modifying it for a test](https://github.com/PoFoLo/PoFoLo-FE/pull/2/commits/5f69bcd1c410a56f0945e6be5b69a2ff79fd9bef)

2024-11-10 16:21 UTC, letthem commented on src/App.tsx
웅웅 확인완료 고생해써요 !!!! 머지할게용 😆

2024-11-10 16:22 UTC, merged